### ISSUE TITLE
Restoring a project results in error: Could not find a part of the path

### ISSUE THREAD

**Issue by chribben** [dotnet/dotnet-docker-preview#13] opened 2016-04-22 11:53 UTC
Getting the error below
```
docker run --rm -it microsoft/dotnet-preview 
dotnet new 
dotnet restore
```
error: Could not find a part of the path '/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/root/proc/189/fd/97'.

**Comment by MichaelSimons** [comment] 2016-04-22 15:23
Thanks for reporting the issue.  The source of the problem is creating the project at the root.  There is an issue tracking this in the CLI repo - https://github.com/dotnet/cli/issues/715.  https://github.com/dotnet/cli/issues/655 is for a related feature that changes the `dotnet new` behavior.

Since this issue is a CLI issue and already being tracked in the CLI repo, I am closing this issue.

**Closed by MichaelSimons** 2016-04-22 15:23 UTC
